name: yaz_client
description: A new Flutter package.
version: 0.0.1
author:
homepage:
  publish_to:none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^1.4.1
  shared_preferences: ^0.5.12+4
  json_annotation: any
  http: ^0.12.2
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.0
  build_runner: any
  pedantic: ^1.9.2
  json_serializable: any
  flutter_test:
    sdk: flutter

flutter: