name: yaz_client
description: Yaz Framework Api For Flutter Client
version: 0.0.5+2
homepage: https://github.com/Mehmetyaz/yaz_client.git
repository: https://github.com/Mehmetyaz/yaz_client.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^2.0.1
  shared_preferences: ^2.0.5
  json_annotation: ^4.0.1
  http: ^0.13.3
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  effective_dart: ^1.3.1
  build_runner: ^2.0.3
  pedantic: ^1.11.0
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

