name: yaz_client
description: Yaz Framework Api For Flutter Client
version: 0.0.5+6
homepage: https://github.com/Mehmetyaz/yaz_client.git
repository: https://github.com/Mehmetyaz/yaz_client.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.7.0"

dependencies:
  mailer: ^5.0.2
  cryptography: ^2.0.2
  shared_preferences: ^2.0.7
  json_annotation: ^4.1.0
  http: ^0.13.3
  yaz: ^0.0.5+8
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  effective_dart: ^1.3.2
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  flutter_test:
    sdk: flutter

