name: yaz_client
description: Yaz Framework Api For Flutter Client
version: 0.0.2+3
homepage: https://github.com/Mehmetyaz/yaz_client.git
repository: https://github.com/Mehmetyaz/yaz_client.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^1.4.1
  shared_preferences: ^0.5.12+4
  json_annotation: ^3.1.0
  http: ^0.12.2
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.0
  build_runner: any
  pedantic: ^1.10.0
  json_serializable: 3.5.1
  flutter_test:
    sdk: flutter

